function E = fresnel1d(x0,E0,lambda,z,x,varargin)

    % x0 must be linear coordinates perpendicular to z
    % lambda is the material wavelength (not freespace)
    
    k = 2*pi/lambda;
    
    E = 1/sqrt(1i*lambda*z)                 ...
        .* exp(1i*k*z)                      ...
        .* trapz(x0,                        ...
            E0 .* exp(1i*k/2/z*(x0-x).^2)   ...
        );