clear; clc
do=3.64;
model = awg.AWG(...
    'Ni',           1,      ...
    'No',           9,      ...
    'lambda_c',     1.55575,...
    'm',            30,     ...
    'N',            40,     ...
    'R',            100,    ...
    'w',            0.4295, ...    %0.4295
    'h',            0.220,  ...
    't',            0.0,    ...
    'd',            1.57,   ...
    'g',            .300,   ...
    'wo',           1.35,   ...
    'wi',           1.35,   ...
    'do',           do,   ...
    'li',           -4*do, ...
    'lo',           0 ...
);

% clf; close all

% r = awg.simulate(model, model.lambda_c);
% 
% awg.plotfield(r.inputField, 'PlotPhase', true)
% awg.plotfield(r.arrayField, 'PlotPhase', true, 'UnwrapPhase', true)
% awg.plotfield(r.outputField, 'PlotPhase', true)


clf; hold on
imscaled('chen_spectrum.png',-7.613310e+04, 3.159272e+01, 0.020128, -0.037122);

r = awg.spectrum(model, 1.536, 1.564, awg.SimulationOptions('ModeType','gaussian'), 'Points', 250, 'Samples',100);

plot(r.wavelength*1e3,10*log10(r.transmission),'k','LineWidth',2)
axis tight
ylim([-45,0])

disp(awg.analyse(r))
