clear; clc

do = 3.50;

model = awg.AWG(...
    'Ni',           1,      ...
    'No',           9,      ...
    'lambda_c',     1.55575,...
    'm',            30,     ...
    'N',            40,     ...
    'R',            100,    ...
    'w',            0.460,  ...
    'h',            0.220,  ...
    't',            0.0,    ...
    'd',            1.6,    ...
    'g',            .300,   ...
    'do',           do,   ...
    'wo',           1.35,   ...
    'wi',           1.35,   ...
    'li',           4*do, ...
    'lo',           -2*do,...
    'core',         'Si',   ...
    'clad',         'SiO2', ...
    'subs',         'SiO2', ...
    'L0',           0       ...
);

model.nc
model.ns
model.Ng
model.dl


clf; hold on
imscaled('chen_spectrum.png',-7.613310e+04, 3.159272e+01, 0.020128, -0.037122);

% % transmission model
% r = awg.spectrum2(model, 1536e-3, 1564e-3, 'Points', 100);
% 
% plot(r.wavelength*1e3,10*log10(r.transmission),'b--','LineWidth',2)
% axis tight
% 
% disp(awg.analyse(r))

% field model
r = awg.spectrum(model, 1536e-3, 1564e-3, awg.SimulationOptions('ModeType','gaussian'), 'Points', 250, 'Samples',100);

plot(r.wavelength*1e3,10*log10(r.transmission),'k','LineWidth',2)
axis tight
ylim([-45,0])

disp(awg.analyse(r))
