%- Fraunhoffer diffraction integral
function u = fraunhoffer(s0,u0,lambda,z,x,varargin)

    % x0 must be planar coordinates perpendicular to z
    % lambda is the material wavelength (not freespace)
    
    k = 2*pi/lambda;
    
    u = 1/sqrt(1i*lambda*z)                 ...
        .* exp(1i*k*z)                      ...
        .* exp(1i*k/2/z*x^2)                ...
        .* trapz(s0,                        ...
            u0 .* exp(-1i*k/z*x*s0)         ...
            .* exp(1i*k/2/z*s0.^2)          ...
        );
    