% Kirchhoff-Fresnel diffraction integral
function [u,x,z] = fresnel(x0,E0,lambda,x,z,varargin)

    % x0 must be planar coordinates perpendicular to z
    % lambda is the material wavelength (not freespace)
    
    k = 2*pi/lambda;
    
    u = 1/sqrt(1i*lambda*z)                 ...
        .* exp(1i*k*z)                      ...
        .* trapz(x0,                        ...
            E0 .* exp(1i*k/2/z*(x0-x).^2)   ...
        );